#
# Cumae Makefile
#
# Copyright (c) 2016 Michelangelo De Simone <michel@ngelo.eu>
#
# This is meant to be included in all the individual
# Makefiles within the src/<something> directories.
#
# As this is a free project, you're free to mock around
# everything but only DEFINES, CFLAGS and LDFLAGS should
# be set in the subprojects Makefiles.
#
# TARGET __MUST__ be set and it should be a globally
# unique target name.
#
# Please see the LICENSE file for the licensing terms.
#
TARGET = sbuca

include ../../Makefile.in
